#### Loading dataset and filtering it

In [4]:
import pandas as pd
from bertopic import BERTopic

In [5]:
#Reading csv 
df = pd.read_csv(r'dataset\datasetA.csv')
#Checking first 5 rows
df.head()

,title,link,date,source,number_of_characters_title,number_of_words_title,day_of_week,month,year,quarter,is_weekend,classes_str
0,Google’s AI is the ‘worst’ for stealing conten...,https://news.google.com/rss/articles/CBMipgFBV...,2025-09-11,Fortune,74,13,Thursday,September,2025,3,False,Sentiment (Positive / Negative Feelings); Huma...
1,Powering the Next Wave of Enterprise Innovatio...,https://news.google.com/rss/articles/CBMitgFBV...,2025-09-11,Silicon Canals,106,16,Thursday,September,2025,3,False,"Creativity, Expression & Identity; Work, Jobs ..."
2,AI a ‘strategic necessity’ law lecturer says,https://news.google.com/rss/articles/CBMiiAFBV...,2025-09-11,qlsproctor.com.au,64,9,Thursday,September,2025,3,False,"Society, Ethics & Culture"
3,Datacom sees AI agents as pivotal to legacy ap...,https://news.google.com/rss/articles/CBMirAFBV...,2025-09-11,ARNnet,70,12,Thursday,September,2025,3,False,"Routine, Lifestyle & Behavior"
4,"Student Blog: Startups, AI, and Lessons from S...",https://news.google.com/rss/articles/CBMijwFBV...,2025-09-11,The University of Queensland,85,13,Thursday,September,2025,3,False,"Learning, Knowledge & Education"

In [12]:
#Selecting just the title, link, and classes_str columns. 
keyData = df[['title', 'classes_str', 'link']]
#Checking nulls 
keyData.isna().sum()

title          0
classes_str    0
link           0
dtype: int64

In [13]:
#Filtering the df so it only selects rows where the classes_str value contains 'Learning, Knowledge & Education'
df2 = keyData[keyData['classes_str'].str.contains('Learning, Knowledge & Education', case=False)]
df2.head()

,title,classes_str,link
4,"Student Blog: Startups, AI, and Lessons from S...","Learning, Knowledge & Education",https://news.google.com/rss/articles/CBMijwFBV...
16,West Alabama school district looks to strength...,"Human Roles; Learning, Knowledge & Education; ...",https://news.google.com/rss/articles/CBMikgFBV...
24,CEO: Proposed data center in College Station f...,"Learning, Knowledge & Education",https://news.google.com/rss/articles/CBMipgFBV...
25,Maine Monitor: ‘Building the plane as we’re fl...,"Learning, Knowledge & Education",https://news.google.com/rss/articles/CBMi3AFBV...
42,Singtel to accelerate employees' AI upskilling...,"Work, Jobs & Economy; Learning, Knowledge & Ed...",https://news.google.com/rss/articles/CBMi1AFBV...

#### Topic Modeling

In [ ]:
#BERTopic only reads lists so i did this
docs = df2["title"].tolist()
print(len(docs))

1946

'Student Blog: Startups, AI, and Lessons from Singapore'

In [15]:
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
topic_model = BERTopic(embedding_model=embedding_model)
topics, probs = topic_model.fit_transform(docs)
topic_model.get_topic_info()

#Topic is the topic number. -1 refers to outliers so it can be ignored.
#Count is how many rows from title fit that topic
#Name is the topic name 
#Representation is the top words that summarize the topic
#Representative_Docs is the example documents that best illustrate the topic

,Topic,Count,Name,Representation,Representative_Docs
0,-1,589,-1_ai_university_the_to,"[ai, university, the, to, of, and, intelligenc...","[Professor and Head, Department of Data Scienc..."
1,0,340,0_classroom_education_school_in,"[classroom, education, school, in, schools, th...",[How AI is changing the work of teachers in th...
2,1,189,1_medical_of_study_artificial,"[medical, of, study, artificial, intelligence,...",[Role and use of race in artificial intelligen...
3,2,72,2_machine_learning_deep_and,"[machine, learning, deep, and, nfl, 2025, scie...","[AI, Data Science and Machine Learning: a Dstl..."
4,3,72,3_creativity_creative_and_human,"[creativity, creative, and, human, ai, in, mus...",[(PDF) How Generative AI Can Augment Human Cre...
5,4,59,4_training_copyright_books_over,"[training, copyright, books, over, authors, an...",[A federal judge sides with Anthropic in lawsu...
6,5,58,5_jobs_job_study_is,"[jobs, job, study, is, college, young, grads, ...","[AI Is a Threat to the Entry-Level Job Market,..."
7,6,37,6_universities_professors_are_utah,"[universities, professors, are, utah, faculty,...","[Opinion: In the AI revolution, universities a..."
8,7,35,7_free_google_training_us,"[free, google, training, us, commits, billion,...",[Google commits US$1bn for AI training at US u...
9,8,34,8_generative_of_leadership_and,"[generative, of, leadership, and, study, empow...",[Educational impacts of generative artificial ...
10,9,29,9_finds_study_models_dangerous,"[finds, study, models, dangerous, is, other, h...","[Like Humans, AI Can Jump to Conclusions, Moun..."
11,10,29,10_microsoft_academy_training_teachers,"[microsoft, academy, training, teachers, copil...",[FSO and Microsoft join forces to accelerate A...
12,11,28,11_cheating_system_cheat_using,"[cheating, system, cheat, using, students, top...",[Opinion | The Only Real Solution to the A.I. ...
13,12,26,12_zero_mit_performance_stocks,"[zero, mit, performance, stocks, bubble, profi...",[95% of organizations got zero return on AI in...
14,13,25,13_college_students_preparing_student,"[college, students, preparing, student, the, a...",[Guiding first-year students through the age o...
15,14,25,14_ethical_ethics_use_education,"[ethical, ethics, use, education, ball, standa...",[Towards responsible artificial intelligence i...
16,15,25,15_students_student_would_university,"[students, student, would, university, anxious...","[University students feel ‘anxious, confused a..."
17,16,24,16_degree_cybersecurity_bachelor_state,"[degree, cybersecurity, bachelor, state, compu...",[New Mexico State University to offer Bachelor...
18,17,21,17_performance_agents_agentic_your,"[performance, agents, agentic, your, mi, comin...",[87% of business leaders think AI agents will ...
19,18,19,18_developers_coding_experienced_software,"[developers, coding, experienced, software, st...",[AI coding tools make developers slower but th...
20,19,19,19_training_gap_hr_report,"[training, gap, hr, report, but, divide, worke...",[HR professionals are tasked with rolling out ...
21,20,18,20_chatbots_warns_chatbot_therapy,"[chatbots, warns, chatbot, therapy, study, ris...",[Study warns of ‘significant risks’ in using A...
22,21,17,21_law_legal_enforcement_firms,"[law, legal, enforcement, firms, for, launches...",[UNESCO’s AI and the Rule of Law Toolkit Trans...
23,22,17,22_google_overviews_study_traffic,"[google, overviews, study, traffic, finds, con...","[Brands dominate Google AI Mode, struggle in A..."
24,23,15,23_complete_guide_industry_2025,"[complete, guide, industry, 2025, in, using, e...",[The Complete Guide to Using AI in the Educati...
25,24,15,24_critical_thinking_eroding_our,"[critical, thinking, eroding, our, tools, mit,...","[AI’s cost to critical thinking, Critical thin..."
26,25,15,25_chatgpt_has_here_than,"[chatgpt, has, here, than, it, integrated, gpt...",[I'm a Teacher Who Has Integrated AI and ChatG...
27,26,13,26_amazon_aws_sagemaker_diverse,"[amazon, aws, sagemaker, diverse, dialects, hy...",[Amazon’s AI Assistant Struggles With Diverse ...
28,27,13,27_uae_curriculum_mohamed_bin,"[uae, curriculum, mohamed, bin, largest, zayed...",[Mohamed bin Zayed University of Artificial In...
29,28,12,28_suicide_chatbots_response_fix,"[suicide, chatbots, response, fix, queries, de...",[Study Says AI Chatbots Need to Fix Suicide Re...
30,29,12,29_performance_high_processing_arm,"[performance, high, processing, arm, enterpris...",[F5 and MinIO expand partnership to power high...
31,30,12,30_chatbots_chats_anthropic_chat,"[chatbots, chats, anthropic, chat, chatbot, us...",[Anthropic will start training its AI models o...
32,31,11,31_language_animals_translate_translation,"[language, animals, translate, translation, co...",[Google Translate Adds AI-Powered Conversation...
33,32,11,32_curiosity_adoption_gap_how,"[curiosity, adoption, gap, how, brokers, genes...",[How To Lead A Team That Leverages AI Tools Wh...
34,33,10,33_nevada_initiative_university_launches,"[nevada, initiative, university, launches, pac...",[Temple College opens manufacturing lab powere...

In [28]:
docDf = topic_model.get_document_info(docs)
docDf.head()

,Document,Topic,Name,Representation,Representative_Docs,Top_n_words,Probability,Representative_document
0,"Student Blog: Startups, AI, and Lessons from S...",13,13_college_students_preparing_student,"[college, students, preparing, student, the, a...",[Guiding first-year students through the age o...,college - students - preparing - student - the...,0.854934,False
1,West Alabama school district looks to strength...,0,0_classroom_education_school_in,"[classroom, education, school, in, schools, th...",[How AI is changing the work of teachers in th...,classroom - education - school - in - schools ...,1.000000,False
2,CEO: Proposed data center in College Station f...,-1,-1_ai_university_the_to,"[ai, university, the, to, of, and, intelligenc...","[Professor and Head, Department of Data Scienc...",ai - university - the - to - of - and - intell...,0.000000,False
3,Maine Monitor: ‘Building the plane as we’re fl...,0,0_classroom_education_school_in,"[classroom, education, school, in, schools, th...",[How AI is changing the work of teachers in th...,classroom - education - school - in - schools ...,1.000000,False
4,Singtel to accelerate employees' AI upskilling...,19,19_training_gap_hr_report,"[training, gap, hr, report, but, divide, worke...",[HR professionals are tasked with rolling out ...,training - gap - hr - report - but - divide - ...,0.807368,False

In [44]:
linksTitles = keyData[['link', 'title']]
merged = pd.merge(docDf, linksTitles, how='inner', left_on='Document', right_on='title')
merged = merged.drop(columns=["title"])
merged = merged.rename(columns={"Document": "Title"})
print(merged.shape)
merged.head()

(1946, 9)

,Title,Topic,Name,Representation,Representative_Docs,Top_n_words,Probability,Representative_document,link
0,"Student Blog: Startups, AI, and Lessons from S...",13,13_college_students_preparing_student,"[college, students, preparing, student, the, a...",[Guiding first-year students through the age o...,college - students - preparing - student - the...,0.854934,False,https://news.google.com/rss/articles/CBMijwFBV...
1,West Alabama school district looks to strength...,0,0_classroom_education_school_in,"[classroom, education, school, in, schools, th...",[How AI is changing the work of teachers in th...,classroom - education - school - in - schools ...,1.000000,False,https://news.google.com/rss/articles/CBMikgFBV...
2,CEO: Proposed data center in College Station f...,-1,-1_ai_university_the_to,"[ai, university, the, to, of, and, intelligenc...","[Professor and Head, Department of Data Scienc...",ai - university - the - to - of - and - intell...,0.000000,False,https://news.google.com/rss/articles/CBMipgFBV...
3,Maine Monitor: ‘Building the plane as we’re fl...,0,0_classroom_education_school_in,"[classroom, education, school, in, schools, th...",[How AI is changing the work of teachers in th...,classroom - education - school - in - schools ...,1.000000,False,https://news.google.com/rss/articles/CBMi3AFBV...
4,Singtel to accelerate employees' AI upskilling...,19,19_training_gap_hr_report,"[training, gap, hr, report, but, divide, worke...",[HR professionals are tasked with rolling out ...,training - gap - hr - report - but - divide - ...,0.807368,False,https://news.google.com/rss/articles/CBMi1AFBV...

In [ ]:
topic1_df = merged[merged['Topic'] == 0]
print(topic1_df.shape)
topic1_df.head()

(340, 9)

,Title,Topic,Name,Representation,Representative_Docs,Top_n_words,Probability,Representative_document,link
1,West Alabama school district looks to strength...,0,0_classroom_education_school_in,"[classroom, education, school, in, schools, th...",[How AI is changing the work of teachers in th...,classroom - education - school - in - schools ...,1.000000,False,https://news.google.com/rss/articles/CBMikgFBV...
3,Maine Monitor: ‘Building the plane as we’re fl...,0,0_classroom_education_school_in,"[classroom, education, school, in, schools, th...",[How AI is changing the work of teachers in th...,classroom - education - school - in - schools ...,1.000000,False,https://news.google.com/rss/articles/CBMi3AFBV...
22,Empowering Minds: The Rise of Artificial Intel...,0,0_classroom_education_school_in,"[classroom, education, school, in, schools, th...",[How AI is changing the work of teachers in th...,classroom - education - school - in - schools ...,0.873694,False,https://news.google.com/rss/articles/CBMiqgFBV...
26,Artificial Intelligence in Higher Education (A...,0,0_classroom_education_school_in,"[classroom, education, school, in, schools, th...",[How AI is changing the work of teachers in th...,classroom - education - school - in - schools ...,0.827049,False,https://news.google.com/rss/articles/CBMikAFBV...
27,Upstart school network focuses on using artifi...,0,0_classroom_education_school_in,"[classroom, education, school, in, schools, th...",[How AI is changing the work of teachers in th...,classroom - education - school - in - schools ...,1.000000,False,https://news.google.com/rss/articles/CBMinwFBV...

#### Scraper