#### Loading dataset and filtering it

In [30]:
import pandas as pd
from bertopic import BERTopic

In [ ]:
#Reading csv 
df = pd.read_csv(r'dataset\datasetA.csv')

,title,link,date,source,number_of_characters_title,number_of_words_title,day_of_week,month,year,quarter,is_weekend,classes_str
0,Google’s AI is the ‘worst’ for stealing conten...,https://news.google.com/rss/articles/CBMipgFBV...,2025-09-11,Fortune,74,13,Thursday,September,2025,3,False,Sentiment (Positive / Negative Feelings); Huma...
1,Powering the Next Wave of Enterprise Innovatio...,https://news.google.com/rss/articles/CBMitgFBV...,2025-09-11,Silicon Canals,106,16,Thursday,September,2025,3,False,"Creativity, Expression & Identity; Work, Jobs ..."
2,AI a ‘strategic necessity’ law lecturer says,https://news.google.com/rss/articles/CBMiiAFBV...,2025-09-11,qlsproctor.com.au,64,9,Thursday,September,2025,3,False,"Society, Ethics & Culture"
3,Datacom sees AI agents as pivotal to legacy ap...,https://news.google.com/rss/articles/CBMirAFBV...,2025-09-11,ARNnet,70,12,Thursday,September,2025,3,False,"Routine, Lifestyle & Behavior"
4,"Student Blog: Startups, AI, and Lessons from S...",https://news.google.com/rss/articles/CBMijwFBV...,2025-09-11,The University of Queensland,85,13,Thursday,September,2025,3,False,"Learning, Knowledge & Education"

In [32]:
#Selecting just the title and classes_str columns. Put in a new dataframe so its less confusing for the rest of the code
titles_and_classes = df[['title', 'classes_str']]
#Checking nulls 
titles_and_classes.isna().sum()

title          0
classes_str    0
dtype: int64

In [33]:
#Filtering the df so it only selects rows where the classes_str value contains 'Learning, Knowledge & Education'
df2 = titles_and_classes[titles_and_classes['classes_str'].str.contains('Learning, Knowledge & Education', case=False)]
df2.head()

,title,classes_str
4,"Student Blog: Startups, AI, and Lessons from S...","Learning, Knowledge & Education"
16,West Alabama school district looks to strength...,"Human Roles; Learning, Knowledge & Education; ..."
24,CEO: Proposed data center in College Station f...,"Learning, Knowledge & Education"
25,Maine Monitor: ‘Building the plane as we’re fl...,"Learning, Knowledge & Education"
42,Singtel to accelerate employees' AI upskilling...,"Work, Jobs & Economy; Learning, Knowledge & Ed..."

#### Testing Various Topic Modeling Techniques

In [34]:
#BERTopic only reads lists so i did this
docs = df2["title"].tolist()
print(len(docs))

1946

In [ ]:
#Default BERTopic Model 
topic_model = BERTopic()
topics, probs = topic_model.fit_transform(docs)
topic_model.get_topic_info()
"""
Topic is the topic number. -1 refers to outliers so it can be ignored.
Count is how many rows from title fit that topic
Name is the topic name 
Representation is the top words that summarize the topic
Representative_Docs is the example documents that best illustrate the topic"""

,Topic,Count,Name,Representation,Representative_Docs
0,-1,627,-1_ai_the_and_to,"[ai, the, and, to, of, university, learning, a...",[Google embraces AI in the classroom with new ...
1,0,333,0_classroom_education_school_in,"[classroom, education, school, in, schools, th...",[How Wisconsin teachers are navigating artific...
2,1,188,1_medical_of_study_artificial,"[medical, of, study, artificial, and, health, ...",[Application and ethical implication of genera...
3,2,69,2_creativity_creative_and_human,"[creativity, creative, and, human, music, in, ...",[AI and Art Collide in This Engineering Course...
4,3,58,3_training_copyright_books_authors,"[training, copyright, books, authors, over, an...",[Judge dismisses authors’ copyright lawsuit ag...
5,4,55,4_universities_higher_the_are,"[universities, higher, the, are, is, why, prof...","[The AI balancing act: universities, innovatio..."
6,5,39,5_university_degree_cybersecurity_engineering,"[university, degree, cybersecurity, engineerin...",[USC Viterbi School of Engineering and the USC...
7,6,37,6_jobs_study_stanford_young,"[jobs, study, stanford, young, workers, job, m...",[AI is already cutting jobs — but only one age...
8,7,34,7_study_finds_models_dangerous,"[study, finds, models, dangerous, is, to, safe...",[Leading AI models show up to 96% blackmail ra...
9,8,31,8_microsoft_academy_training_tech,"[microsoft, academy, training, tech, teachers,...","[Tech Giants, AFT Launch National AI Training ..."
10,9,30,9_machine_learning_2025_science,"[machine, learning, 2025, science, biscuit, ds...","[AI, Data Science and Machine Learning: a Dstl..."
11,10,29,10_cheating_system_cheat_using,"[cheating, system, cheat, using, students, top...",[Opinion | The Only Real Solution to the A.I. ...
12,11,26,11_ethical_ethics_wollongong_education,"[ethical, ethics, wollongong, education, unive...",[Towards responsible artificial intelligence i...
13,12,25,12_chatgpt_users_chat_chatbots,"[chatgpt, users, chat, chatbots, chatgpts, cha...",[I'm a teacher who has integrated AI and ChatG...
14,13,25,13_zero_mit_performance_bubble,"[zero, mit, performance, bubble, stocks, retur...",[95% of organizations got zero return on AI in...
15,14,25,14_performance_agents_agentic_reveals,"[performance, agents, agentic, reveals, mi, re...",[Why AI agents need performance reviews (and e...
16,15,23,15_college_students_student_atlanta,"[college, students, student, atlanta, ga, emor...",[Guiding first-year students through the age o...
17,16,22,16_students_university_student_confused,"[students, university, student, confused, anxi...",[Frequent use of artificial intelligence may h...
18,17,20,17_overviews_google_study_content,"[overviews, google, study, content, googles, f...","[Brands dominate Google AI Mode, struggle in A..."
19,18,20,18_chatbots_warns_study_chatbot,"[chatbots, warns, study, chatbot, therapy, ris...","[Knowledge, use and perceptions of artificial ..."
20,19,19,19_training_gap_report_but,"[training, gap, report, but, divide, workers, ...",[HR professionals are tasked with rolling out ...
21,20,18,20_developers_coding_experienced_software,"[developers, coding, experienced, software, st...",[AI coding tools made some experienced softwar...
22,21,18,21_law_legal_enforcement_for,"[law, legal, enforcement, for, firms, launches...",[Pre-law student survey unmasks fears of artif...
23,22,18,22_google_us_commits_billion,"[google, us, commits, billion, training, unive...",[Google commits US$1bn for AI training at US u...
24,23,17,23_free_training_midlands_west,"[free, training, midlands, west, startup, spri...",[West Midlands Authority to provide free AI tr...
25,24,15,24_complete_guide_industry_2025,"[complete, guide, industry, 2025, in, using, e...",[The Complete Guide to Using AI in the Educati...
26,25,14,25_amazon_aws_sagemaker_amazons,"[amazon, aws, sagemaker, amazons, diverse, dia...",[Amazon’s AI assistant struggles with diverse ...
27,26,14,26_critical_thinking_eroding_our,"[critical, thinking, eroding, our, hinders, wa...","[AI’s cost to critical thinking, Critical thin..."
28,27,14,27_uae_curriculum_mohamed_bin,"[uae, curriculum, mohamed, bin, zayed, saudi, ...",[Mohamed bin Zayed University of Artificial In...
29,28,14,28_job_grads_college_graduates,"[job, grads, college, graduates, recent, marke...",[Recent college graduates face challenging job...
30,29,13,29_suicide_chatbots_response_fix,"[suicide, chatbots, response, fix, queries, de...",[Study says AI chatbots need to fix suicide re...
31,30,12,30_highperformance_performance_enterprise_faster,"[highperformance, performance, enterprise, fas...",[F5 and MinIO expand partnership to power high...
32,31,12,31_generative_responses_analysis_influencing,"[generative, responses, analysis, influencing,...",[Research on the Influencing Factors of Genera...
33,32,12,32_adoption_curiosity_gap_how,"[adoption, curiosity, gap, how, barrier, chain...",[How To Lead A Team That Leverages AI Tools Wh...
34,33,10,33_generative_empowers_lo_embedding,"[generative, empowers, lo, embedding, depend, ...",[Study: Generative AI results depend on user p...
35,34,10,34_food_sustainable_explainable_deep,"[food, sustainable, explainable, deep, advanci...",[Evaluation of deep learning models using expl...

In [36]:
#Work in progress
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
topic_model = BERTopic(embedding_model=embedding_model)
topics, probs = topic_model.fit_transform(docs)
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,744,-1_ai_education_artificial_intelligence,"[ai, education, artificial, intelligence, to, ...",[AI in the classroom: How China is bringing ar...
1,0,186,0_medical_of_study_artificial,"[medical, of, study, artificial, intelligence,...",[Role and use of race in artificial intelligen...
2,1,85,1_study_finds_knowledge_content,"[study, finds, knowledge, content, can, ai, go...","[Like Humans, AI Can Jump to Conclusions, Moun..."
3,2,74,2_classroom_teacher_teaching_the,"[classroom, teacher, teaching, the, how, my, a...",[How AI is impacting teachers and students in ...
4,3,70,3_creativity_creative_and_human,"[creativity, creative, and, human, music, ai, ...",[AI and Art Collide in This Engineering Course...
5,4,58,4_copyright_training_books_authors,"[copyright, training, books, authors, anthropi...",[A federal judge sides with Anthropic in lawsu...
6,5,41,5_university_degree_cybersecurity_bachelor,"[university, degree, cybersecurity, bachelor, ...",[New Mexico State University to offer Bachelor...
7,6,39,6_universities_are_faculty_the,"[universities, are, faculty, the, why, technol...",[Faculty Demand Voice in AI Decisions as Unive...
8,7,39,7_jobs_study_young_stanford,"[jobs, study, young, stanford, workers, job, m...",[AI is already cutting jobs — but only one age...
9,8,37,8_chatbots_suicide_study_warns,"[chatbots, suicide, study, warns, response, fi...",[Study says AI chatbots need to fix suicide re...
10,9,37,9_machine_learning_2025_science,"[machine, learning, 2025, science, dstl, biscu...","[AI, Data Science and Machine Learning: a Dstl..."
11,10,31,10_education_is_ncea_can,"[education, is, ncea, can, watch, opinion, sha...",[Does Bentley Systems’ (BSY) AI Education Pled...
12,11,30,11_microsoft_academy_training_copilot,"[microsoft, academy, training, copilot, union,...","[Tech Giants, AFT Launch National AI Training ..."
13,12,29,12_students_student_university_frequent,"[students, student, university, frequent, anxi...",[Frequent use of artificial intelligence may h...
14,13,29,13_cheating_system_cheat_using,"[cheating, system, cheat, using, students, cri...",[Opinion | The Only Real Solution to the A.I. ...
15,14,26,14_ethical_ethics_wollongong_use,"[ethical, ethics, wollongong, use, ball, educa...",[Towards responsible artificial intelligence i...
16,15,24,15_zero_mit_performance_stocks,"[zero, mit, performance, stocks, bubble, retur...",[95% of organizations got zero return on AI in...
17,16,24,16_college_preparing_students_student,"[college, preparing, students, student, offeri...","[At Harvard Convocation, College Dean David De..."
18,17,24,17_chatgpt_users_chat_chats,"[chatgpt, users, chat, chats, has, here, than,...",[I'm a Teacher Who Has Integrated AI and ChatG...
19,18,22,18_performance_agents_agentic_reveals,"[performance, agents, agentic, reveals, mi, un...","[Rogue agents: As CEOs pile into AI, IBM says ..."
20,19,21,19_training_gap_hr_report,"[training, gap, hr, report, workers, tasked, d...",[40% of workers now use AI but major gap exist...
21,20,17,20_amazon_aws_ucl_sagemaker,"[amazon, aws, ucl, sagemaker, web, services, a...",[Amazon’s AI Assistant Struggles With Diverse ...
22,21,17,21_developers_coding_experienced_software,"[developers, coding, experienced, software, to...",[AI coding tools make developers slower but th...
23,22,17,22_google_us_commits_billion,"[google, us, commits, billion, training, unive...",[Google commits US$1bn for AI training at US u...
24,23,17,23_law_legal_enforcement_firms,"[law, legal, enforcement, firms, launches, for...",[UNESCO’s AI and the Rule of Law Toolkit Trans...
25,24,15,24_critical_thinking_eroding_our,"[critical, thinking, eroding, our, mit, tools,...","[AI’s cost to critical thinking, Critical thin..."
26,25,15,25_complete_guide_industry_2025,"[complete, guide, industry, 2025, in, using, e...",[The Complete Guide to Using AI in the Educati...
27,26,14,26_school_public_schools_intelligence,"[school, public, schools, intelligence, artifi...","[Lake Oswego School District sets guidelines, ..."
28,27,13,27_uae_curriculum_mohamed_bin,"[uae, curriculum, mohamed, bin, largest, zayed...",[Mohamed bin Zayed University of Artificial In...
29,28,13,28_district_school_districts_classrooms,"[district, school, districts, classrooms, mexi...",[This Houston-area school district is embracin...
30,29,13,29_generative_responses_influencing_empirical,"[generative, responses, influencing, empirical...",[Generative artificial intelligence in educati...
31,30,13,30_food_deep_sustainable_explainable,"[food, deep, sustainable, explainable, learnin...",[Evaluation of deep learning models using expl...
32,31,13,31_grads_college_job_blame,"[grads, college, job, blame, graduates, recent...",[Recent college graduates face challenging job...
33,32,12,32_curiosity_adoption_gap_how,"[curiosity, adoption, gap, how, brokers, perpl...",[How To Lead A Team That Leverages AI Tools Wh...
34,33,12,33_free_midlands_mayor_training,"[free, midlands, mayor, training, west, adults...",[West Midlands Authority to provide free AI tr...
35,34,11,34_literacy_teachers_adoption_modeling,"[literacy, teachers, adoption, modeling, chine...",[Bridging AI literacy and UTAUT constructs: st...
36,35,11,35_higher_education_challenges_driving,"[higher, education, challenges, driving, oppor...","[Monash University, Indonesia EduVate 2025: Dr..."
37,36,11,36_generative_empowers_talent_duca,"[generative, empowers, talent, duca, undersgen...","[Generative AI – transforming talent, learning..."
38,37,11,37_12_kansas_future_education,"[12, kansas, future, education, schools, door,...",[How AI Will Reshape K-12 and Higher Education...
39,38,11,38_classroom_teachers_artificial_intelligence,"[classroom, teachers, artificial, intelligence...","[Teachers, district leaders working to figure ..."
40,39,10,39_performance_high_processing_arm,"[performance, high, processing, arm, boost, pa...",[F5 and MinIO expand partnership to power high...
41,40,10,40_schools_me_education_challenges,"[schools, me, education, challenges, future, i...",[Generation Ready: Building the Foundations fo...

In [37]:
#Work in progress
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
topic_model = BERTopic(embedding_model=embedding_model)
topics, probs = topic_model.fit_transform(docs)
topics = topic_model.reduce_topics(docs, nr_topics=10)  
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,548,-1_ai_of_the_to,"[ai, of, the, to, and, artificial, intelligenc...",[Navigating lifelong learning in the age of ar...
1,0,583,0_in_ai_education_the,"[in, ai, education, the, to, artificial, intel...",[(PDF) Artificial Intelligence in Education Tr...
2,1,476,1_study_ai_of_and,"[study, ai, of, and, in, intelligence, artific...",[The role of generative AI tools in case-based...
3,2,104,2_creativity_generative_and_ai,"[creativity, generative, and, ai, in, of, the,...",[Does generative AI actually enhance creativit...
4,3,100,3_training_copyright_ai_use,"[training, copyright, ai, use, for, ethical, b...","[A New Look at Fair Use: Anthropic, Meta, and ..."
5,4,57,4_chatbots_chatgpt_study_suicide,"[chatbots, chatgpt, study, suicide, ai, to, us...",[Study says AI chatbots need to fix suicide re...
6,5,28,5_cheating_using_ai_the,"[cheating, using, ai, the, system, students, c...","[The AI Cheating Epidemic, AI Cheating, New wa..."
7,6,25,6_amazon_performance_aws_ai,"[amazon, performance, aws, ai, nvidia, with, a...",[Renaissance uses generative AI on AWS to acce...
8,7,15,7_critical_thinking_eroding_the,"[critical, thinking, eroding, the, tools, ai, ...","[AI’s cost to critical thinking, Critical thin..."
9,8,10,8_learning_explainable_artificial_intelligence,"[learning, explainable, artificial, intelligen...",[Evaluation of deep learning models using expl...