#### Loading dataset and filtering it

In [ ]:
import pandas as pd
from bertopic import BERTopic

In [17]:
#Reading csv 
df = pd.read_csv('datasetA.csv')
#Checking first 5 rows
df.head()

,title,link,date,source,number_of_characters_title,number_of_words_title,day_of_week,month,year,quarter,is_weekend,classes_str
0,Google’s AI is the ‘worst’ for stealing conten...,https://news.google.com/rss/articles/CBMipgFBV...,2025-09-11,Fortune,74,13,Thursday,September,2025,3,False,Sentiment (Positive / Negative Feelings); Huma...
1,Powering the Next Wave of Enterprise Innovatio...,https://news.google.com/rss/articles/CBMitgFBV...,2025-09-11,Silicon Canals,106,16,Thursday,September,2025,3,False,"Creativity, Expression & Identity; Work, Jobs ..."
2,AI a ‘strategic necessity’ law lecturer says,https://news.google.com/rss/articles/CBMiiAFBV...,2025-09-11,qlsproctor.com.au,64,9,Thursday,September,2025,3,False,"Society, Ethics & Culture"
3,Datacom sees AI agents as pivotal to legacy ap...,https://news.google.com/rss/articles/CBMirAFBV...,2025-09-11,ARNnet,70,12,Thursday,September,2025,3,False,"Routine, Lifestyle & Behavior"
4,"Student Blog: Startups, AI, and Lessons from S...",https://news.google.com/rss/articles/CBMijwFBV...,2025-09-11,The University of Queensland,85,13,Thursday,September,2025,3,False,"Learning, Knowledge & Education"

In [18]:
#Selecting just the title and classes_str columns. Put in a new dataframe so its less confusing for the rest of the code
titles_and_classes = df[['title', 'classes_str']]
#Checking nulls 
titles_and_classes.isna().sum()

title          0
classes_str    0
dtype: int64

In [19]:
#Filtering the df so it only selects rows where the classes_str value contains 'Learning, Knowledge & Education'
df2 = titles_and_classes[titles_and_classes['classes_str'].str.contains('Learning, Knowledge & Education', case=False)]
df2.head()

,title,classes_str
4,"Student Blog: Startups, AI, and Lessons from S...","Learning, Knowledge & Education"
16,West Alabama school district looks to strength...,"Human Roles; Learning, Knowledge & Education; ..."
24,CEO: Proposed data center in College Station f...,"Learning, Knowledge & Education"
25,Maine Monitor: ‘Building the plane as we’re fl...,"Learning, Knowledge & Education"
42,Singtel to accelerate employees' AI upskilling...,"Work, Jobs & Economy; Learning, Knowledge & Ed..."

#### Testing Various Topic Modeling Techniques

In [20]:
#BERTopic only reads lists so i did this
docs = df2["title"].tolist()
print(len(docs))

1946

In [ ]:
#Default BERTopic Model 
topic_model = BERTopic()
topics, probs = topic_model.fit_transform(docs)
topic_model.get_topic_info()
#Topic is the topic number. -1 refers to outliers so it can be ignored.
#Count is how many rows from title fit that topic
#Name is the topic name 
#Representation is the top words that summarize the topic
#Representative_Docs is the example documents that best illustrate the topic

,Topic,Count,Name,Representation,Representative_Docs
0,-1,778,-1_ai_the_intelligence_artificial,"[ai, the, intelligence, artificial, in, educat...",[The School of Human and Artificial Intelligen...
1,0,189,0_medical_of_study_artificial,"[medical, of, study, artificial, health, and, ...",[Detection of breast cancer using machine lear...
2,1,83,1_classroom_teacher_teaching_how,"[classroom, teacher, teaching, how, ai, the, t...",[How AI is impacting teachers and students in ...
3,2,70,2_creativity_creative_and_human,"[creativity, creative, and, human, music, desi...",[AI and art collide in this engineering course...
4,3,64,3_machine_learning_deep_and,"[machine, learning, deep, and, 2025, data, sci...",[AI and machine learning for engineering desig...
5,4,58,4_copyright_training_books_authors,"[copyright, training, books, authors, over, an...",[Judge dismisses authors’ copyright lawsuit ag...
6,5,50,5_jobs_job_study_is,"[jobs, job, study, is, stanford, workers, coll...",[Stanford study says AI is wiping out jobs for...
7,6,41,6_universities_professors_are_utah,"[universities, professors, are, utah, faculty,...",[Faculty Demand Voice in AI Decisions as Unive...
8,7,39,7_study_finds_models_is,"[study, finds, models, is, dangerous, to, ai, ...","[Like Humans, AI Can Jump to Conclusions, Moun..."
9,8,35,8_education_is_future_ncea,"[education, is, future, ncea, ai, watch, opini...",[Does Bentley Systems’ (BSY) AI Education Pled...
10,9,34,9_college_students_university_nevada,"[college, students, university, nevada, future...",['I think AI is the future': Adrian College of...
11,10,31,10_generative_leadership_of_and,"[generative, leadership, of, and, gifu, aug, r...",[Generative artificial intelligence in educati...
12,11,30,11_google_free_training_us,"[google, free, training, us, commits, billion,...",[Google commits US$1bn for AI training at US u...
13,12,29,12_cheating_system_cheat_using,"[cheating, system, cheat, using, students, top...",[Opinion | The Only Real Solution to the A.I. ...
14,13,27,13_zero_mit_performance_bubble,"[zero, mit, performance, bubble, stocks, retur...",[95% of organizations got zero return on AI in...
15,14,27,14_ethical_ethics_responsible_education,"[ethical, ethics, responsible, education, scho...",[Towards responsible artificial intelligence i...
16,15,26,15_degree_cybersecurity_engineering_computing,"[degree, cybersecurity, engineering, computing...",[New Mexico university to offer state's first ...
17,16,25,16_microsoft_academy_training_join,"[microsoft, academy, training, join, launch, p...",[FSO and Microsoft join forces to accelerate A...
18,17,25,17_students_student_university_frequent,"[students, student, university, frequent, conf...",[Frequent use of artificial intelligence may h...
19,18,24,18_chatgpt_users_chatbots_chatgpts,"[chatgpt, users, chatbots, chatgpts, chats, ha...",[I'm a teacher who has integrated AI and ChatG...
20,19,22,19_performance_agents_agentic_mi,"[performance, agents, agentic, mi, reviews, ag...",[The AI Agent Arms Race: Latest OutSystems AI ...
21,20,20,20_chatbots_warns_chatbot_study,"[chatbots, warns, chatbot, study, risks, physi...",[Study warns of ‘significant risks’ in using A...
22,21,19,21_training_gap_adma_report,"[training, gap, adma, report, but, divide, wor...",[HR professionals are tasked with rolling out ...
23,22,18,22_higher_education_inclusion_elearning,"[higher, education, inclusion, elearning, chal...",[Cross-border Higher Education Cooperation und...
24,23,17,23_overviews_google_study_googles,"[overviews, google, study, googles, traffic, f...","[Brands dominate Google AI Mode, struggle in A..."
25,24,17,24_developers_coding_experienced_software,"[developers, coding, experienced, software, st...",[AI coding tools made some experienced softwar...
26,25,16,25_law_legal_enforcement_firms,"[law, legal, enforcement, firms, for, launches...",[Pre-law student survey unmasks fears of artif...
27,26,16,26_school_public_intelligence_artificial,"[school, public, intelligence, artificial, sch...","[Lake Oswego School District sets guidelines, ..."
28,27,15,27_critical_thinking_eroding_our,"[critical, thinking, eroding, our, mit, tools,...","[AI’s cost to critical thinking, Critical thin..."
29,28,15,28_amazon_aws_sagemaker_web,"[amazon, aws, sagemaker, web, services, divers...",[Amazon’s AI Assistant Struggles With Diverse ...
30,29,13,29_curriculum_bin_mohamed_zayed,"[curriculum, bin, mohamed, zayed, uae, saudi, ...",[Mohamed bin Zayed University of Artificial In...
31,30,13,30_highperformance_performance_enterprise_faster,"[highperformance, performance, enterprise, fas...",[F5 and MinIO expand partnership to power high...
32,31,13,31_complete_guide_industry_2025,"[complete, guide, industry, 2025, using, in, e...",[The Complete Guide to Using AI in the Educati...
33,32,12,32_districts_school_district_federal,"[districts, school, district, federal, classro...",[School districts take mixed approach to AI as...
34,33,12,33_literacy_teachers_chinese_we,"[literacy, teachers, chinese, we, digital, ado...",[AI Literacy is Imperative for Classroom Succe...
35,34,12,34_suicide_chatbots_response_fix,"[suicide, chatbots, response, fix, queries, de...",[Study says AI chatbots need to fix suicide re...
36,35,11,35_adoption_curiosity_gap_how,"[adoption, curiosity, gap, how, eager, hampers...",[How To Lead A Team That Leverages AI Tools Wh...

In [ ]:
#Work in progress
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
topic_model = BERTopic(embedding_model=embedding_model)
topics, probs = topic_model.fit_transform(docs)
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,754,-1_ai_education_the_in,"[ai, education, the, in, to, artificial, intel...",[New school: What artificial intelligence mean...
1,0,186,0_medical_of_study_artificial,"[medical, of, study, artificial, intelligence,...",[(PDF) BMC Medical Education Artificial intell...
2,1,83,1_classroom_teacher_teaching_the,"[classroom, teacher, teaching, the, how, ai, s...",[An AI-Powered Framework for Assessing Teacher...
3,2,81,2_study_finds_google_ai,"[study, finds, google, ai, knowledge, models, ...","[Like Humans, AI Can Jump to Conclusions, Moun..."
4,3,70,3_creativity_creative_and_human,"[creativity, creative, and, human, ai, music, ...",[AI and art collide in this engineering course...
5,4,60,4_copyright_training_books_authors,"[copyright, training, books, authors, anthropi...",[A federal judge sides with Anthropic in lawsu...
6,5,51,5_machine_learning_nfl_2025,"[machine, learning, nfl, 2025, props, predicti...","[Chiefs vs. Chargers in Brazil NFL props, odds..."
7,6,40,6_universities_professors_are_utah,"[universities, professors, are, utah, faculty,...",[Faculty Demand Voice in AI Decisions as Unive...
8,7,40,7_school_district_schools_guidelines,"[school, district, schools, guidelines, public...",[How Topeka Public Schools is implementing art...
9,8,39,8_university_degree_state_cybersecurity,"[university, degree, state, cybersecurity, bac...",[New Mexico State University to offer Bachelor...
10,9,35,9_generative_of_leadership_and,"[generative, of, leadership, and, in, empowers...",[Educational impacts of generative artificial ...
11,10,33,10_jobs_study_stanford_young,"[jobs, study, stanford, young, workers, job, m...",[AI is already cutting jobs – but only one age...
12,11,31,11_education_can_is_opinion,"[education, can, is, opinion, future, ai, pote...",[You can still outpace AI: Wharton professor r...
13,12,30,12_microsoft_academy_training_teachers,"[microsoft, academy, training, teachers, copil...","[Tech Giants, AFT Launch National AI Training ..."
14,13,29,13_cheating_system_cheat_using,"[cheating, system, cheat, using, students, top...",[Opinion | The Only Real Solution to the A.I. ...
15,14,26,14_ethical_ethics_wollongong_use,"[ethical, ethics, wollongong, use, ball, educa...",[Towards responsible artificial intelligence i...
16,15,25,15_zero_mit_performance_stocks,"[zero, mit, performance, stocks, bubble, retur...",[95% of organizations got zero return on AI in...
17,16,24,16_students_university_student_confused,"[students, university, student, confused, linc...",[Frequent use of artificial intelligence may h...
18,17,22,17_college_students_preparing_student,"[college, students, preparing, student, the, p...",[A Student’s Guide to College and Career in th...
19,18,22,18_performance_agents_agentic_mi,"[performance, agents, agentic, mi, reviews, un...",[87% of business leaders think AI agents will ...
20,19,20,19_chatbots_warns_chatbot_study,"[chatbots, warns, chatbot, study, risks, physi...",[Study warns of ‘significant risks’ in using A...
21,20,18,20_google_us_commits_billion,"[google, us, commits, billion, training, unive...",[Google commits US$1bn for AI training at US u...
22,21,17,21_law_legal_enforcement_firms,"[law, legal, enforcement, firms, for, launches...",[UNESCO’s AI and the Rule of Law Toolkit Trans...
23,22,16,22_developers_coding_experienced_software,"[developers, coding, experienced, software, so...",[AI coding tools make developers slower but th...
24,23,15,23_uae_curriculum_largest_bin,"[uae, curriculum, largest, bin, mohamed, zayed...",[UAE schools to introduce Artificial Intellige...
25,24,15,24_training_adma_hr_gap,"[training, adma, hr, gap, report, divide, but,...",[40% of workers now use AI but major gap exist...
26,25,15,25_chatgpt_has_here_than,"[chatgpt, has, here, than, integrated, gpt, re...",[I'm a Teacher Who Has Integrated AI and ChatG...
27,26,14,26_critical_thinking_eroding_our,"[critical, thinking, eroding, our, loc, hinder...","[AI’s cost to critical thinking, Critical thin..."
28,27,14,27_amazon_aws_sagemaker_dialects,"[amazon, aws, sagemaker, dialects, arabic, hp,...",[Amazon’s AI Assistant Struggles With Diverse ...
29,28,14,28_complete_guide_industry_2025,"[complete, guide, industry, 2025, in, using, e...",[The Complete Guide to Using AI in the Educati...
30,29,14,29_literacy_teachers_adoption_modeling,"[literacy, teachers, adoption, modeling, chine...",[Bridging AI literacy and UTAUT constructs: st...
31,30,13,30_suicide_chatbots_response_fix,"[suicide, chatbots, response, fix, queries, in...",[Study says AI chatbots need to fix suicide re...
32,31,13,31_grads_college_job_blame,"[grads, college, job, blame, graduates, recent...",[Recent college graduates face challenging job...
33,32,12,32_classroom_artificial_intelligence_english,"[classroom, artificial, intelligence, english,...",[Artificial intelligence is revolutionising cl...
34,33,11,33_free_midlands_mayor_west,"[free, midlands, mayor, west, training, adults...",[West Midlands Authority to provide free AI tr...
35,34,11,34_performance_high_processing_arm,"[performance, high, processing, arm, boost, pa...",[F5 and MinIO expand partnership to power high...
36,35,11,35_higher_education_challenges_driving,"[higher, education, challenges, driving, oppor...","[Monash University, Indonesia EduVate 2025: Dr..."
37,36,11,36_curiosity_adoption_gap_how,"[curiosity, adoption, gap, how, brokers, genes...",[How To Lead A Team That Leverages AI Tools Wh...
38,37,11,37_food_sustainable_explainable_deep,"[food, sustainable, explainable, deep, advanci...",[Advanced hybrid machine learning models with ...

In [ ]:
#Work in progress
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
topic_model = BERTopic(embedding_model=embedding_model)
topics, probs = topic_model.fit_transform(docs)
topics = topic_model.reduce_topics(docs, nr_topics=10)  
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,610,-1_ai_of_to_the,"[ai, of, to, the, and, in, intelligence, unive...",[Google embraces AI in the classroom with new ...
1,0,562,0_in_ai_education_the,"[in, ai, education, the, to, artificial, intel...","[Artificial intelligence in the classroom, The..."
2,1,245,1_and_machine_of_learning,"[and, machine, of, learning, artificial, intel...",[10 Years of Artificial Intelligence and Machi...
3,2,200,2_study_ai_to_finds,"[study, ai, to, finds, performance, jobs, is, ...",[Stanford study says AI is wiping out jobs for...
4,3,105,3_creativity_generative_and_ai,"[creativity, generative, and, ai, of, in, the,...",[How generative AI is transforming beauty: the...
5,4,102,4_training_copyright_ai_use,"[training, copyright, ai, use, for, ethical, b...",[A federal judge sides with Anthropic in lawsu...
6,5,57,5_chatbots_chatgpt_study_suicide,"[chatbots, chatgpt, study, suicide, ai, to, ch...",[Study says AI chatbots need to fix suicide re...
7,6,28,6_cheating_using_ai_the,"[cheating, using, ai, the, system, students, c...","[The AI Cheating Epidemic, AI Cheating, New wa..."
8,7,23,7_amazon_performance_aws_ai,"[amazon, performance, aws, ai, with, and, sage...",[Renaissance uses generative AI on AWS to acce...
9,8,14,8_critical_thinking_eroding_the,"[critical, thinking, eroding, the, our, ai, st...","[AI’s cost to critical thinking, Critical thin..."